import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OrderContextProvider } from "@/context/OrderContext";
import Dashboard from "@/components/dashboard";
import PageHeader from "@/components/pageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageHeader />
        <OrderContextProvider>
          {children}
        </OrderContextProvider>
      </body>
    </html>
  );
}
